### ISSUE TITLE
Error in Visual studio 2019

### ISSUE THREAD

**Issue by OliverEncoded** [Reputeless/PerlinNoise#12]
I've been using C++ for a couple of weeks now and wanted to make some world generation, so this seemed to be really great I created a PerlinNoise.hpp and pasted in your code, and no errors except three, all on lines like the one shown below, I'm using Visual Studio 2019 with SFML so I'm just wondering if this is only for G++? 
Thanks :D

![Screenshot_1](https://user-images.githubusercontent.com/86622891/154296518-19b774a8-e299-4f3f-94f5-56e756be660c.png)

**Comment by Reputeless** [comment]
This library requires C++17, so you need to set the compiler flag `/std:c++17`.
The default setting in Visual Studio 2019 is `/std:c++14`.

**Comment by OliverEncoded** [comment]
aah ok, got it thanks 😄
