### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by Vxerz** [Reputeless/PerlinNoise#13]
![image](https://github.com/Reputeless/PerlinNoise/assets/109004204/2704f1e0-941f-4588-a729-0c042184d2fc)
I just included the hpp file and didn't do anything else and I'm getting this long list of errors, I'm assuming I'm missing something but I don't know what

**Comment by Reputeless** [comment]
The errors you are encountering are due to the use of Visual Studio in its default C++14 mode. My library requires features that are available in C++17. Please change your project settings to use the C++17 standard. This should resolve the issues you are experiencing.
