### ISSUE TITLE
Persistence and Frequency in Octaves

### ISSUE THREAD

**Issue by devsammi3** [Reputeless/PerlinNoise#3]
It seems I can't provide numbers for persistence and frequency? Meaning I'd have to by default, calculate for one octave at a time in order to achieve that. Am I missing something?

**Comment by Reputeless** [comment]
Frequency can be adjusted by scaling x, y, and z.
I will bring persistence in the next update.
Thanks for your feedback :-)

**Comment by Reputeless** [comment]
v3.0.0 now supports persistence.
