### ISSUE TITLE
is_arithmetic_v not a member of 'std'

### ISSUE THREAD

**Issue by patrikpatrik** [Reputeless/PerlinNoise#8]
Sorry if this has been listed before but I'm getting an `error: 'is_arithmetic_v' is not a member of 'std'` using CodeBlocks 20.03 Windows 10 x64.

**Comment by Reputeless** [comment]
`std::is_arithmetic_v`  is a C++17 feature.
Make sure your compiler supports it and compile with C++17 flag.
